
import jsPDF from 'jspdf';
import { EAFFormDetails } from '../types';

export const generateEAF = (data: EAFFormDetails) => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  // Constants
  const PAGE_WIDTH = 210;
  const PAGE_HEIGHT = 297;
  const MARGIN = 10;
  const CONTENT_WIDTH = PAGE_WIDTH - (MARGIN * 2); // 190mm
  
  // Colors & Styles
  const BLACK = "#000000";
  const WHITE = "#FFFFFF";

  // --- HELPER: Create Fillable Text Field ---
  const createTextField = (
    id: string, 
    x: number, 
    y: number, 
    w: number, 
    h: number, 
    value: string, 
    isMultiline: boolean = false,
    fontSize: number = 10
  ) => {
    // We access the low-level AcroForm API for maximum control
    // @ts-ignore - types for AcroForm are sometimes missing in standard definitions
    const textField = new doc.AcroForm.TextField();
    textField.Rect = [x, y, w, h];
    textField.multiline = isMultiline;
    textField.value = value || "";
    textField.fieldName = id;
    textField.fontSize = fontSize;
    textField.maxFontSize = fontSize; // Prevent auto-scaling to huge text
    textField.color = BLACK;
    // Appearance settings for a "Modern" look (clean, no heavy bevels)
    textField.appearanceState = "On"; 
    
    doc.addField(textField);
  };

  // --- HELPER: Create Fillable Checkbox ---
  const createCheckbox = (id: string, x: number, y: number, w: number, h: number, checked: boolean = false) => {
    // @ts-ignore
    const checkBox = new doc.AcroForm.CheckBox();
    checkBox.Rect = [x, y, w, h];
    checkBox.fieldName = id;
    checkBox.appearanceState = checked ? "On" : "Off";
    doc.addField(checkBox);
  };

  // --- HELPER: Draw Cell with Label and Form Field ---
  const drawCell = (
    x: number, 
    y: number, 
    w: number, 
    h: number, 
    label: string, 
    value: string = "", 
    options: { 
      bg?: string, 
      labelBold?: boolean, 
      valueBold?: boolean,
      border?: boolean,
      fieldId?: string, // If present, makes this a fillable field
      multiline?: boolean
    } = {}
  ) => {
    // Background
    if (options.bg) {
      doc.setFillColor(options.bg);
      doc.rect(x, y, w, h, "F");
    }
    
    // Border
    doc.setDrawColor(0);
    doc.setLineWidth(0.3);
    if (options.border !== false) {
      doc.rect(x, y, w, h);
    }

    // Label
    if (label) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(BLACK);
      doc.text(label, x + 2, y + 4);
    }

    // Value / Field
    if (options.fieldId) {
      // Calculate field area (below label)
      const fieldY = y + 5; 
      const fieldH = h - 6; 
      const fieldX = x + 1;
      const fieldW = w - 2;

      createTextField(
        options.fieldId, 
        fieldX, 
        fieldY, 
        fieldW, 
        fieldH, 
        String(value), 
        options.multiline || false
      );
    } else if (value) {
      // Static Text Fallback
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(BLACK);
      const splitValue = doc.splitTextToSize(String(value), w - 4);
      doc.text(splitValue, x + 2, y + 9);
    }

    return y + h;
  };

  let currentY = MARGIN;

  // --- 1. TITLE ---
  doc.setLineWidth(0.5);
  doc.rect(MARGIN, currentY, CONTENT_WIDTH, 8);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("EOC EXPENDITURE AUTHORIZATION FORM", PAGE_WIDTH / 2, currentY + 5.5, { align: "center" });
  currentY += 8;

  // --- 2. HEADER GRID ---
  const ROW_H = 10; // Slightly taller to accommodate input fields nicely
  const COL_1_W = CONTENT_WIDTH * 0.45;
  const COL_2_W = CONTENT_WIDTH * 0.30;
  const COL_3_W = CONTENT_WIDTH * 0.25;

  // Line 1
  drawCell(MARGIN, currentY, COL_1_W, ROW_H, "Event:", data.event, { fieldId: "event_name" });
  drawCell(MARGIN + COL_1_W, currentY, COL_2_W, ROW_H, "Date:", data.date, { fieldId: "date" });
  // EAF Box (Spans 2 rows) - Static EAF ID generated by system, usually not editable, but we make it editable for flexibility
  drawCell(MARGIN + COL_1_W + COL_2_W, currentY, COL_3_W, ROW_H * 2, "EAF#:", (data.taskNumber ? `${data.taskNumber}-001` : ""), { fieldId: "eaf_number" }); 
  
  currentY += ROW_H;

  // Line 2
  const TASK_W = COL_1_W * 0.6;
  const OP_W = COL_1_W * 0.4;
  
  drawCell(MARGIN, currentY, TASK_W, ROW_H, "EMBC Task #:", data.taskNumber, { fieldId: "task_number" });
  drawCell(MARGIN + TASK_W, currentY, OP_W, ROW_H, "Op Period:", data.operationalPeriod, { fieldId: "op_period" });
  drawCell(MARGIN + COL_1_W, currentY, COL_2_W, ROW_H, "Time:", data.time, { fieldId: "time" });
  
  currentY += ROW_H + 2;

  // Line 3
  drawCell(MARGIN, currentY, CONTENT_WIDTH, ROW_H, "Requesting Organization/Community:", data.organization, { fieldId: "org_name" });
  currentY += ROW_H;

  // Line 4
  const COL_3_EQ = CONTENT_WIDTH / 3;
  // Auth Rep Checkbox area - simplified to just Name field for PDF form
  drawCell(MARGIN, currentY, COL_3_EQ, ROW_H, "Authorized Representative (Check if Yes):", "", { border: true });
  createCheckbox("auth_rep_check", MARGIN + COL_3_EQ - 10, currentY + 3, 5, 5, !!data.authRepName);

  drawCell(MARGIN + COL_3_EQ, currentY, COL_3_EQ, ROW_H, "Name:", data.authRepName, { fieldId: "rep_name" });
  drawCell(MARGIN + (COL_3_EQ * 2), currentY, COL_3_EQ, ROW_H, "EOC Location:", data.authRepLocation, { fieldId: "location" });
  currentY += ROW_H;

  // Line 5
  drawCell(MARGIN, currentY, COL_3_EQ, ROW_H, "Telephone:", data.phone, { fieldId: "phone" });
  drawCell(MARGIN + COL_3_EQ, currentY, COL_3_EQ, ROW_H, "Fax:", data.fax, { fieldId: "fax" });
  drawCell(MARGIN + (COL_3_EQ * 2), currentY, COL_3_EQ, ROW_H, "Email:", data.email, { fieldId: "email" });
  currentY += ROW_H;

  // --- 3. DESCRIPTION ---
  const DESC_H = 80;
  // Draw the Container
  doc.rect(MARGIN, currentY, CONTENT_WIDTH, DESC_H);
  
  // Label inside box
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("Description of Expenditure: (include nature of goods and/or services, desired outcome, location...)", MARGIN + 2, currentY + 4);
  
  // THE BIG FILLABLE AREA
  createTextField(
    "description_main", 
    MARGIN + 1, 
    currentY + 5, 
    CONTENT_WIDTH - 2, 
    DESC_H - 6, 
    data.description, 
    true // Multiline!
  );

  currentY += DESC_H;

  // --- 4. AMOUNT ---
  const AMOUNT_H = 12;
  const HALF_W = CONTENT_WIDTH / 2;

  // Amount Requested
  drawCell(MARGIN, currentY, HALF_W, AMOUNT_H, "Amount Requested:", "", { border: true });
  createTextField(
    "amount_requested", 
    MARGIN + 40, 
    currentY + 2, 
    HALF_W - 45, 
    8, 
    data.amount > 0 ? `$${data.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}` : ""
  );

  // Expenditure Not to Exceed
  const notToExceed = data.amount > 0 ? data.amount * 1.10 : 0;
  drawCell(MARGIN + HALF_W, currentY, HALF_W, AMOUNT_H, "Expenditure Not to Exceed (Req + 10%):", "", { border: true });
  createTextField(
    "amount_max", 
    MARGIN + HALF_W + 65, 
    currentY + 2, 
    HALF_W - 70, 
    8, 
    notToExceed > 0 ? `$${notToExceed.toLocaleString(undefined, { minimumFractionDigits: 2 })}` : ""
  );
  
  currentY += AMOUNT_H;

  // --- 5. EOC APPROVALS ---
  const APP_LABEL_W = 20;
  const APP_COL_W = (CONTENT_WIDTH - APP_LABEL_W) / 2;
  const APP_BLOCK_H = 24; 
  
  // Label Column
  doc.setFillColor(30, 30, 30);
  doc.rect(MARGIN, currentY, APP_LABEL_W, APP_BLOCK_H, "F");
  doc.setTextColor(WHITE);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("EOC", MARGIN + 2, currentY + 8);
  doc.text("Approvals", MARGIN + 2, currentY + 13);
  doc.setTextColor(BLACK);

  // EOC Headers
  drawCell(MARGIN + APP_LABEL_W, currentY, APP_COL_W, 8, "Approved for Processing by:", "", { border: true });
  drawCell(MARGIN + APP_LABEL_W + APP_COL_W, currentY, APP_COL_W, 8, "Expenditure Request Approved by:", "", { border: true });
  
  // Row 2: Position Fields
  const row2Y = currentY + 8;
  drawCell(MARGIN + APP_LABEL_W, row2Y, APP_COL_W, 8, "Position:", "", { fieldId: "eoc_proc_pos", border: true });
  drawCell(MARGIN + APP_LABEL_W + APP_COL_W, row2Y, APP_COL_W, 8, "Position (Director):", "EOC Director", { fieldId: "eoc_dir_pos", border: true });

  // Row 3: Signature/Date Fields
  const row3Y = currentY + 16;
  drawCell(MARGIN + APP_LABEL_W, row3Y, APP_COL_W, 8, "Date/Time:", "", { fieldId: "eoc_proc_date", border: true });
  drawCell(MARGIN + APP_LABEL_W + APP_COL_W, row3Y, APP_COL_W, 8, "Date/Time:", "", { fieldId: "eoc_dir_date", border: true });

  currentY += APP_BLOCK_H;

  // --- 6. PREOC APPROVALS ---
  // Label Column
  doc.setFillColor(30, 30, 30);
  doc.rect(MARGIN, currentY, APP_LABEL_W, APP_BLOCK_H, "F");
  doc.setTextColor(WHITE);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("PREOC", MARGIN + 2, currentY + 8);
  doc.text("Approvals", MARGIN + 2, currentY + 13);
  doc.setTextColor(BLACK);

  // Row 1
  const pRow1Y = currentY;
  drawCell(MARGIN + APP_LABEL_W, pRow1Y, APP_COL_W, 8, "Approved for Processing by:", "", { border: true });
  // Add "Not Approved" Checkbox manually
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.text("Not Approved", MARGIN + APP_LABEL_W + 60, pRow1Y + 5);
  createCheckbox("preoc_not_approved", MARGIN + APP_LABEL_W + 55, pRow1Y + 2.5, 3, 3);

  drawCell(MARGIN + APP_LABEL_W + APP_COL_W, pRow1Y, APP_COL_W, 8, "Expenditure Authorized by:", "", { border: true });

  // Row 2
  const pRow2Y = currentY + 8;
  drawCell(MARGIN + APP_LABEL_W, pRow2Y, APP_COL_W, 8, "Position:", "Operations Section Chief", { fieldId: "preoc_ops_pos", border: true });
  drawCell(MARGIN + APP_LABEL_W + APP_COL_W, pRow2Y, APP_COL_W, 8, "Position:", "PREOC Director", { fieldId: "preoc_dir_pos", border: true });

  // Row 3
  const pRow3Y = currentY + 16;
  drawCell(MARGIN + APP_LABEL_W, pRow3Y, APP_COL_W, 8, "Date/Time:", "", { fieldId: "preoc_ops_date", border: true });
  drawCell(MARGIN + APP_LABEL_W + APP_COL_W, pRow3Y, APP_COL_W, 8, "Date/Time:", "", { fieldId: "preoc_dir_date", border: true });

  currentY += APP_BLOCK_H;

  // --- 7. DISTRIBUTION ---
  const DIST_H = 30; // More space for checkboxes
  doc.rect(MARGIN, currentY, CONTENT_WIDTH, DIST_H);
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("Distribution:", MARGIN + 2, currentY + 6);

  // Checkbox Helper
  const drawDistOption = (colX: number, rowY: number, id: string, label: string) => {
    createCheckbox(id, colX, rowY, 3.5, 3.5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(label, colX + 6, rowY + 3);
  };

  const col1X = MARGIN + 30;
  const col2X = MARGIN + 105;
  let distY = currentY + 5;
  const distGap = 6;

  // Col 1
  drawDistOption(col1X, distY, "dist_eoc_dir", "EOC Director");
  drawDistOption(col1X, distY + distGap, "dist_eoc_ops", "EOC Operations Section");
  drawDistOption(col1X, distY + (distGap*2), "dist_eoc_plan", "EOC Planning Section");
  drawDistOption(col1X, distY + (distGap*3), "dist_eoc_log", "EOC Logistics Section");
  drawDistOption(col1X, distY + (distGap*4), "dist_eoc_fin", "EOC Finance & Admin Section");

  // Col 2
  drawDistOption(col2X, distY, "dist_preoc_dir", "PREOC Director");
  drawDistOption(col2X, distY + distGap, "dist_preoc_ops", "PREOC Operations Section");
  drawDistOption(col2X, distY + (distGap*2), "dist_preoc_plan", "PREOC Planning Section");
  drawDistOption(col2X, distY + (distGap*3), "dist_preoc_log", "PREOC Logistics Section");
  drawDistOption(col2X, distY + (distGap*4), "dist_preoc_fin", "PREOC Finance & Admin Section");

  currentY += DIST_H + 5;

  // --- 8. COMMENTS ---
  doc.setFont("helvetica", "bold");
  doc.text("Comments:", MARGIN, currentY);
  
  createTextField("comments_field", MARGIN, currentY + 2, CONTENT_WIDTH, 20, "", true);

  // --- FOOTER ---
  const FOOTER_Y = PAGE_HEIGHT - 10;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("May 2018 (Generated via Innomergence)", MARGIN, FOOTER_Y);
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("EOC 530", PAGE_WIDTH - MARGIN - 15, FOOTER_Y);

  // Save
  doc.save(`EAF_530_${(data.taskNumber || "draft").replace(/[^a-z0-9]/gi, '_')}.pdf`);
};
